### ISSUE TITLE
等高布局怎么老是忘？因为你没理解它的思路

### ISSUE THREAD

**Issue by bowencool** [bowencool/blog#2]
本文只讲最难记的那一种思路。

# 任务拆分
等高分为以下2步：
  1. 顶部对齐
  2. 消除高度差

# 实操
## 第一步：顶部对齐
可以选择`vertical-algin`:
``` css
.content {
   vertical-align: top;
   display: inline-block;
}
```
也可以用`float`:
``` css
.content {
  float: left;
}
```
